<?php
use Unirest;

if (class_exists('Unirest\Exception') === false) {
  require_once("./" . drupal_get_path('module', 'sagenda') . '/assets/vendor/mashape/unirest-php/src/Unirest.php');
}

// declare global variable
define('SAGENDA_API_URL', 'https://sagenda.net/api/v3/');

/**
 * Implements hook_theme().
 */
function sagenda_theme($existing, $type, $theme, $path)
{
  return [
    'sagenda_booking_calendar' => [
      'variables' => [
        'data' => null,
      ],
    ],
  ];
}

/**
 * Callback to get Sagenda Calendar Config.
 *
 * @return mixed
 */
function get_sagenda_calendar_config()
{
  $sagenda_config = \Drupal::config('sagenda.settings');
  $data['token'] = $sagenda_config->get('token');
  $languages = $this->container->get('language_manager')->getLanguages();
  
  try {
    $body = "grant_type=api_token&api_token=" . $sagenda_config->get('token');
    $response = Unirest\Request::post(
      SAGENDA_API_URL . "token",
      array(
        "Content-Type" => "application/json",
        "Accept" => "application/json"
      ),
      $body
    );
  } catch (Exception $e) {
    echo "Oups, I did it again : " . $e->getMessage();
  }

  $data['defaultView'] = $sagenda_config->get('defaultView');
  $data['removeMonthViewButton'] = convertBoolean($sagenda_config->get('removeMonthViewButton'));
  $data['removeWeekViewButton'] = convertBoolean($sagenda_config->get('removeWeekViewButton'));
  $data['removeDayViewButton'] = convertBoolean($sagenda_config->get('removeDayViewButton'));

  $data['token'] = $response->body->access_token;
  $data['date'] = $sagenda_config->get('date');
  $data['time'] = $sagenda_config->get('time');
  $data['weekstartson'] = $sagenda_config->get('weekstartson');
  $data['api_url'] = SAGENDA_API_URL;
  $path = \Drupal::urlGenerator()->generateFromRoute('<front>', [], ['absolute' => true, 'language' => $languages['en']]);
  $module_path = drupal_get_path('module', 'sagenda');
  $data['angular_path'] = substr($path, 0, strripos($path, "/")) . "/" . $module_path . '/angular/';
  $data['language'] = \Drupal::languageManager()->getCurrentLanguage()->getId();

  return $data;
}

function convertBoolean($value)
{
  if ($value === 0) {
    return false;
  }
  return true;
}